from .pick_meat import PickMeatEnv
from .camera_alignment import CameraAlignmentEnv
from .stack_cube import StackCubeEnv
from .strike_cube import StrikeCubeEnv
from .place_food import PlaceFoodEnv
from .two_robots_stack_cube import TwoRobotsStackCubeEnv
from .three_robots_stack_cube import ThreeRobotsStackCubeEnv
from .pass_shoe import PassShoeEnv
from .lift_barrier import LiftBarrierEnv
from .take_photo import TakePhotoEnv
from .long_pipeline_delivery import LongPipelineDeliveryEnv