from .pick_meat import solve as solvePickMeat
from .camera_alignment import solve as solveCameraAlignment
from .stack_cube import solve as solveStackCube
from .strike_cube import solve as solveStrikeCube
from .place_food import solve as solvePlaceFood
from .pass_shoe import solve as solvePassShoe
from .two_robots_stack_cube import solve as solveTwoRobotsStackCube
from .three_robots_stack_cube import solve as solveThreeRobotsStackCube
from .lift_barrier import solve as solveLiftBarrier
from .take_photo import solve as solveTakePhoto
from .long_pipeline_delivery import solve as solveLongPipelineDelivery